# Generated by Django 3.2.10 on 2023-09-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadiths', '0002_auto_20230831_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith_id', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('chapter_no', models.IntegerField()),
                ('hadith_no', models.IntegerField()),
                ('chapter', models.CharField(max_length=255)),
                ('chain_indx', models.IntegerField()),
                ('text_ar', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
    ]
