# Generated by Django 3.2.10 on 2023-09-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadiths', '0004_hadithsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='chain_indx',
            field=models.CharField(max_length=255),
        ),
    ]
