# Generated by Django 3.2.10 on 2023-09-05 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hadiths', '0005_alter_hadith_chain_indx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadith',
            name='id',
        ),
        migrations.AlterField(
            model_name='hadith',
            name='hadith_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadiths.hadithsource'),
        ),
    ]
