# Generated by Django 3.2.10 on 2023-09-05 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hadiths', '0006_auto_20230905_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hadiths_read_number',
        ),
        migrations.CreateModel(
            name='ProfileHadithSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadiths_read_number', models.IntegerField(default=0)),
                ('hadith_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadiths.hadithsource')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadiths.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='sources',
            field=models.ManyToManyField(through='hadiths.ProfileHadithSource', to='hadiths.HadithSource'),
        ),
    ]
