# Generated by Django 3.2.10 on 2023-09-06 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hadiths', '0007_auto_20230905_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileHadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadiths.hadith')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadiths.profile')),
            ],
        ),
    ]
